language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
  - "12"
  - "8"
  - lts/*
before_script:
  - npm install
  - npm install nyc@13 --global
script:
  # - npm run build
  - nyc npm test
after_success:
  - npm install coveralls@~3.0.0 --global
  - nyc report --reporter=text-lcov | coveralls
before_deploy:
  - lerna run clean
  - lerna run build:prod
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
      node_js: lts/*
      os: linux
    - stage: test
    - stage: deploy
      node_js: lts/*
      os: linux
      deploy:
        skip_cleanup: true
        provider: script
        script: npx lerna publish --skip-git
        on:
          branch: master
